"""create tables

Revision ID: db691f54fc3a
Revises: 
Create Date: 2024-11-24 22:34:46.498047

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import models

# revision identifiers, used by Alembic.
revision: str = "db691f54fc3a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_applications",
        sa.Column(
            "client_id",
            sa.String(length=50),
            nullable=False,
            comment="クライアントID",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=True,
            comment="アプリケーション名",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "details",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "content", sa.String(length=100), nullable=False, comment="内容"
        ),
        sa.Column(
            "client_id",
            sa.String(length=50),
            nullable=False,
            comment="クライアントID",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["discord_applications.client_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "logs",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID",
        ),
        sa.Column("detail_id", sa.Integer(), nullable=False, comment="詳細ID"),
        sa.Column(
            "start_time",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="表示開始時間",
        ),
        sa.Column(
            "end_time", sa.DateTime(), nullable=True, comment="表示終了時間"
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="削除済"
        ),
        sa.Column(
            "created_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            models.mixins.UTCToJSTType(),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(
            ["detail_id"],
            ["details.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    op.drop_table("details")
    op.drop_table("discord_applications")
    # ### end Alembic commands ###
